# Site settings

title: "PCjs Machines"
email: Jeff@pcjs.org
description: >
  Welcome to PCjs, home of the original IBM PC in a web browser.
  PCjs provides a variety of computer emulators written in JavaScript, including PCx86 for x86-based machines
  (up through the 80386), C1Pjs for the 6502-based Ohio Scientific Challenger 1P, PC8080 for 8080-based machines
  such as Space Invaders and the DEC VT100 Terminal, and PDPjs with support for PDP-10 and PDP-11 machines.
  PCjs also provides an archive of selected historical PC software, publications, and reference materials.
baseurl: ""                 # "/pcjs" when using http://jeffpar.github.io or "" when using http://www.pcjs.org 
url: "http://www.pcjs.org"  # "http://jeffpar.github.io" or "http://www.pcjs.org"
twitter_username: jeffpar
github_username:  jeffpar

left_brace: "{"
right_brace: "}"
encoding: UTF-8

# Build settings

exclude: ["index.html", "**/index.html", "bin", "logs", "node_modules", "projects", "src", "tmp", "videos", "web", "**/archive", "**/ecp", "**/c64", "**/private", "**/restricted", "**/src", "**/tmp", "**/unlisted", ".git", ".idea"]
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Custom site settings

pcjs:
  domain: pcjs.org    # whereas site.url is used for linking purposes, site.pcjs.domain is used for display purposes
  version: 1.35.1     # IMPORTANT: keep pcjs.version in sync with package.json:version
  compiled: true      # by default, the compiled pcjs.version scripts will be used (eg, pcx86.js or pcx86-dbg.js)
  c1p_scripts:        # if pcjs.compiled is false, the following scripts will be included instead, in the order listed
    - /modules/shared/lib/defines.js
    - /modules/shared/lib/nodebug.js
    - /modules/shared/lib/dumpapi.js
    - /modules/shared/lib/reportapi.js
    - /modules/shared/lib/strlib.js
    - /modules/shared/lib/usrlib.js
    - /modules/shared/lib/weblib.js
    - /modules/shared/lib/component.js
    - /modules/c1pjs/lib/defines.js
    - /modules/c1pjs/lib/panel.js
    - /modules/c1pjs/lib/cpu.js
    - /modules/c1pjs/lib/rom.js
    - /modules/c1pjs/lib/ram.js
    - /modules/c1pjs/lib/keyboard.js
    - /modules/c1pjs/lib/video.js
    - /modules/c1pjs/lib/serial.js
    - /modules/c1pjs/lib/disk.js
    - /modules/c1pjs/lib/debugger.js
    - /modules/c1pjs/lib/computer.js
    - /modules/shared/lib/embed.js
  pcx86_scripts:
    - /modules/shared/lib/defines.js
    - /modules/shared/lib/nodebug.js
    - /modules/shared/lib/diskapi.js
    - /modules/shared/lib/dumpapi.js
    - /modules/shared/lib/reportapi.js
    - /modules/shared/lib/userapi.js
    - /modules/shared/lib/keys.js
    - /modules/shared/lib/strlib.js
    - /modules/shared/lib/usrlib.js
    - /modules/shared/lib/weblib.js
    - /modules/shared/lib/component.js
    - /modules/pcx86/lib/defines.js
    - /modules/pcx86/lib/x86.js
    - /modules/pcx86/lib/interrupts.js
    - /modules/pcx86/lib/messages.js
    - /modules/pcx86/lib/panel.js
    - /modules/pcx86/lib/bus.js
    - /modules/pcx86/lib/memory.js
    - /modules/pcx86/lib/cpu.js
    - /modules/pcx86/lib/x86seg.js
    - /modules/pcx86/lib/x86cpu.js
    - /modules/pcx86/lib/x86fpu.js
    - /modules/pcx86/lib/x86func.js
    - /modules/pcx86/lib/x86help.js
    - /modules/pcx86/lib/x86mods.js
    - /modules/pcx86/lib/x86ops.js
    - /modules/pcx86/lib/x86op0f.js
    - /modules/pcx86/lib/chipset.js
    - /modules/pcx86/lib/rom.js
    - /modules/pcx86/lib/ram.js
    - /modules/pcx86/lib/keyboard.js
    - /modules/pcx86/lib/video.js
    - /modules/pcx86/lib/parallel.js
    - /modules/pcx86/lib/serial.js
    - /modules/pcx86/lib/mouse.js
    - /modules/pcx86/lib/disk.js
    - /modules/pcx86/lib/fdc.js
    - /modules/pcx86/lib/hdc.js
    - /modules/shared/lib/debugger.js
    - /modules/pcx86/lib/debugger.js
    - /modules/pcx86/lib/computer.js
    - /modules/shared/lib/state.js
    - /modules/shared/lib/embed.js
    - /modules/shared/lib/save.js
  pc8080_scripts:
    - /modules/shared/lib/defines.js
    - /modules/shared/lib/nodebug.js
    - /modules/shared/lib/dumpapi.js
    - /modules/shared/lib/reportapi.js
    - /modules/shared/lib/userapi.js
    - /modules/shared/lib/keys.js
    - /modules/shared/lib/strlib.js
    - /modules/shared/lib/usrlib.js
    - /modules/shared/lib/weblib.js
    - /modules/shared/lib/component.js
    - /modules/pc8080/lib/defines.js
    - /modules/pc8080/lib/cpudef.js
    - /modules/pc8080/lib/messages.js
    - /modules/pc8080/lib/panel.js
    - /modules/pc8080/lib/bus.js
    - /modules/pc8080/lib/memory.js
    - /modules/pc8080/lib/cpu.js
    - /modules/pc8080/lib/cpustate.js
    - /modules/pc8080/lib/cpuops.js
    - /modules/pc8080/lib/chipset.js
    - /modules/pc8080/lib/rom.js
    - /modules/pc8080/lib/ram.js
    - /modules/pc8080/lib/keyboard.js
    - /modules/pc8080/lib/video.js
    - /modules/pc8080/lib/serial.js
    - /modules/shared/lib/debugger.js
    - /modules/pc8080/lib/debugger.js
    - /modules/pc8080/lib/computer.js
    - /modules/shared/lib/state.js
    - /modules/shared/lib/embed.js
  pdp10_scripts:
    - /modules/shared/lib/defines.js
    - /modules/shared/lib/nodebug.js
    - /modules/shared/lib/dumpapi.js
    - /modules/shared/lib/reportapi.js
    - /modules/shared/lib/userapi.js
    - /modules/shared/lib/keys.js
    - /modules/shared/lib/strlib.js
    - /modules/shared/lib/usrlib.js
    - /modules/shared/lib/weblib.js
    - /modules/shared/lib/component.js
    - /modules/pdp10/lib/defines.js
    - /modules/pdp10/lib/messages.js
    - /modules/pdp10/lib/panel.js
    - /modules/pdp10/lib/bus.js
    - /modules/pdp10/lib/device.js
    - /modules/pdp10/lib/memory.js
    - /modules/pdp10/lib/cpu.js
    - /modules/pdp10/lib/cpustate.js
    - /modules/pdp10/lib/cpuops.js
    - /modules/pdp10/lib/rom.js
    - /modules/pdp10/lib/ram.js
    - /modules/pdp10/lib/serial.js
    - /modules/shared/lib/debugger.js
    - /modules/pdp10/lib/debugger.js
    - /modules/pdp10/lib/macro10.js
    - /modules/pdp10/lib/computer.js
    - /modules/shared/lib/state.js
    - /modules/shared/lib/embed.js
  pdp11_scripts:
    - /modules/shared/lib/defines.js
    - /modules/shared/lib/nodebug.js
    - /modules/shared/lib/dumpapi.js
    - /modules/shared/lib/reportapi.js
    - /modules/shared/lib/userapi.js
    - /modules/shared/lib/keys.js
    - /modules/shared/lib/strlib.js
    - /modules/shared/lib/usrlib.js
    - /modules/shared/lib/weblib.js
    - /modules/shared/lib/component.js
    - /modules/pdp11/lib/defines.js
    - /modules/pdp11/lib/messages.js
    - /modules/pdp11/lib/panel.js
    - /modules/pdp11/lib/bus.js
    - /modules/pdp11/lib/device.js
    - /modules/pdp11/lib/memory.js
    - /modules/pdp11/lib/cpu.js
    - /modules/pdp11/lib/cpustate.js
    - /modules/pdp11/lib/cpuops.js
    - /modules/pdp11/lib/rom.js
    - /modules/pdp11/lib/ram.js
    - /modules/pdp11/lib/keyboard.js
    - /modules/pdp11/lib/serial.js
    - /modules/pdp11/lib/pc11.js
    - /modules/pdp11/lib/disk.js
    - /modules/pdp11/lib/drive.js
    - /modules/pdp11/lib/rk11.js
    - /modules/pdp11/lib/rl11.js
    - /modules/pdp11/lib/rx11.js
    - /modules/shared/lib/debugger.js
    - /modules/pdp11/lib/debugger.js
    - /modules/pdp11/lib/computer.js
    - /modules/shared/lib/state.js
    - /modules/shared/lib/embed.js
